### ISSUE TITLE
Doesn't work if version of node is not specified

### ISSUE THREAD

**Issue by adrienthiery** [Osedea/nodock#15]
Need to add : 

```
services:
    node:
        build:
            args:
                node_version: 6.7.0 
```

To `override.yml`
